# Generated by Django 5.2 on 2025-04-24 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='average_ctc',
            field=models.FloatField(blank=True, help_text='Average CTC for freshers in LPA', null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='employee_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='founded_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='headquarters',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='industry',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='company',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='role',
            name='average_ctc',
            field=models.FloatField(blank=True, help_text='CTC for this role in LPA', null=True),
        ),
        migrations.AddField(
            model_name='role',
            name='job_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='role',
            name='openings_per_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('rating', models.FloatField(help_text='Rating out of 5')),
                ('pros', models.TextField(blank=True, null=True)),
                ('cons', models.TextField(blank=True, null=True)),
                ('work_life_balance', models.IntegerField(blank=True, help_text='Rating out of 10', null=True)),
                ('culture', models.IntegerField(blank=True, help_text='Rating out of 10', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='companies.company')),
            ],
        ),
    ]
