# Generated by Django 5.2 on 2025-04-24 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_average_ctc_company_employee_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='review_text',
            field=models.TextField(blank=True),
        ),
    ]
