# Generated by Django 5.2 on 2025-04-24 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_review_review_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.FloatField(blank=True, help_text='Rating out of 5', null=True),
        ),
    ]
